now we sign the aide binary and /etc/aide.conf as well, and make sure they are not tampered with when doing a check; added aide-edit-conf to check the sig before editing the config and then signing it again immediately after

diff --git a/aidecheck b/aidecheck
--- a/aidecheck
+++ b/aidecheck
@@ -21,31 +21,35 @@ databasenew_file=$(egrep '^database_out=' /etc/aide.conf | sed "s|file:@@{DBDIR}
 
 export GNUPGHOME=/root/.gnupg
 
-echo "AIDE+gpg integrity check for ${hostname} beginning (`date`)"
-echo ""
+gpg_verify() {
+    if [ ! -f ${1} ]; then
+        printf "**** Error: No GPG signature found for the AIDE ${2}!\n"
+        printf "**** Unabel to verify; your system may be compromised or incorrectly configured!\n"
+        exit 1
+    fi
+
+    printf "\nVerifying ${2}: "
+    ${gpg} --verify ${1}
+    if [ "$?" != "0" ]; then
+        printf "************************************************************\n"
+        printf "GPG signature FAILED!  Your ${2} has been tampered with!\n"
+        printf "************************************************************\n"
+        exit 1
+    fi
+}
+
+printf "AIDE+gpg integrity check for ${hostname} beginning (`date`)\n"
 if [ ! -e ${database_file} ] ; then
-    echo "**** Error: AIDE database for ${hostname} not found."
-    echo "**** Run 'aideinit' to create the database file."
+    printf "**** Error: AIDE database for ${hostname} not found.\n"
+    printf "**** Run 'aideinit' to create the database file.\n"
 else
     if [ -f /etc/aide.conf ]; then
-        if [ -f ${database_file}.sig ]; then
-	    pushd ${dbdir} >/dev/null
-	        echo "Verifying the GPG signature on the database..."
-		echo ""
-	        ${gpg} --verify ${database_file}.sig
-		echo ""
-		if [ "$?" == "1" ]; then
-		    echo "************************************************************"
-		    echo "GPG signature FAILED!  Your database has been tampered with!"
-		    echo "************************************************************"
-		    exit 1
-		fi
-	    popd >/dev/null
-	else
-	    echo "**** Error: No GPG signature found for the AIDE database!"
-	    echo "**** Unable to verify database; your system may be compromised or incorrectly configured!"
-	    exit 1
-	fi
+        gpg_verify /etc/aide.conf.sig configuration
+        gpg_verify ${aide}.sig binary
+        pushd ${dbdir} >/dev/null
+            gpg_verify ${database_file}.sig database
+        popd >/dev/null
+        printf "\nVerifying AIDE database...\n"
         nice -20 ${aide} --check -B "report_url=file:/var/lib/aide/reports/${fname}.report" 2>/dev/null
     fi
 fi
diff --git a/aideinit b/aideinit
--- a/aideinit
+++ b/aideinit
@@ -8,7 +8,7 @@
 # $Id$
 
 # variables
-version="1.0"
+version="@pkg_version@"
 host="`hostname`"
 gpg="/usr/bin/gpg"
 aide="/usr/sbin/aide"
@@ -86,13 +86,27 @@ else
 fi
 
 signfile() {
-    echo ${PASS1} | ${gpg} -u aide@${host} --passphrase-fd stdin --no-tty --batch --detach-sign ${database_file}
+    [[ -f ${1}.sig ]] && rm -f ${1}.sig
+    echo ${PASS1} | ${gpg} -u aide@${host} --passphrase-fd stdin --no-tty --batch --detach-sign ${1}
     if [ "$?" == "1" ]; then
         printf "FATAL:  Error occurred when creating the signature file!\n\n"
         exit 1
     fi
-    chmod 0600 ${database_file}.sig
+    chmod 0600 ${1}.sig
+    [[ ! -f ${1}.sig ]] && {
+        printf "FATAL: Signature file ${1}.sig was not created! Aborting.\n\n"
+        exit 1
+    }
 }
+
+# first we sign the AIDE binary so on subsequent checks, before calling it,
+# we can verify the signature
+printf "Signing the AIDE binary...\n"
+signfile  ${aide}
+
+# likewise for the configuration file
+printf "Signing the AIDE configuration file...\n"
+signfile /etc/aide.conf
 
 printf "Initializing the AIDE database... this may take a minute or two.\n"
 
@@ -105,11 +119,7 @@ pushd ${dbdir} >/dev/null 2>&1
     fi
     # create the signature file; we don't have to ask for the passphrase here, we've already got it
     [[ -f ${database_file}.sig ]] && rm -f ${database_file}.sig
-    signfile
-    [[ ! -f ${database_file}.sig ]] && {
-        printf "FATAL: Signature was not created!  Aborting.\n\n"
-        exit 1
-    }
+    signfile ${database_file}
     printf "Database successfully signed.\n\n"
 popd >/dev/null 2>&1
 
diff --git a/aideupdate b/aideupdate
--- a/aideupdate
+++ b/aideupdate
@@ -8,7 +8,7 @@
 # $Id$
 
 # variables
-version="1.0"
+version="@pkg_version@"
 gpg="/usr/bin/gpg"
 aide="/usr/sbin/aide"
 fname="aide-`hostname`-`date +%Y%m%d-%H%M%S`"
@@ -39,13 +39,13 @@ if [ -f ${database_file} ]; then
     newfile="${fname}.db"
     if [ -f ${database_file}.sig ]; then
         # do an integrity check
-	${gpg} --verify ${database_file}.sig
-	if [ "$?" == "1" ]; then
-	    printf "************************************************************\n"
-	    printf "GPG signature FAILED!  Your database has been tampered with!\n"
-	    printf "************************************************************\n"
-	    exit 1
-	fi
+    ${gpg} --verify ${database_file}.sig
+    if [ "$?" != "0" ]; then
+        printf "************************************************************\n"
+        printf "GPG signature FAILED!  Your database has been tampered with!\n"
+        printf "************************************************************\n"
+        exit 1
+    fi
     else
         printf "**************************************************************\n"
         printf "No GPG signature file found!  Your system may be compromised\n"
@@ -54,7 +54,7 @@ if [ -f ${database_file} ]; then
         printf "**************************************************************\n"
         exit 1
     fi
-    
+
     # this function signs the aide.db with gpg
     signfile() {
         unset gpgpass
@@ -68,7 +68,7 @@ if [ -f ${database_file} ]; then
         fi
         chmod 0600 ${database_file}.sig
     }
-    
+
     cp -f ${database_file} ${newfile} 
     ${aide} --update -B "report_url=file:/var/lib/aide/reports/${fname}.report"
     # rename the outbound file since we prefer operating on the "inbound" file
